# Generated by Django 4.1.7 on 2023-04-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_img",
            field=models.ImageField(
                default="default/default-user.jpg", upload_to="user_img"
            ),
        ),
    ]
