# Generated by Django 4.1.7 on 2023-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_customuser_is_admin_alter_customuser_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_img",
            field=models.ImageField(
                blank=True, default="default/default-user.jpg", upload_to="user_img"
            ),
        ),
    ]
