# Generated by Django 4.1.7 on 2023-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geolocation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
