# Generated by Django 4.1.7 on 2023-05-08 07:57

from django.db import migrations, models
#import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="tags",
        ),
        # migrations.AlterField(
        #     model_name="tag",
        #     name="id",
        #     # field=models.UUIDField(
        #     #     default=uuid.uuid4, editable=False, primary_key=True, serialize=False
        #     # ),
#        ),
    ]
