# Generated by Django 4.1.7 on 2023-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0002_remove_bookmark_tags_alter_upload_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="tags",
            field=models.ManyToManyField(to="the_archive.tag"),
        ),
    ]
