# Generated by Django 4.1.7 on 2023-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0002_remove_bookmark_tags_alter_tag_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.CharField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
    ]
