# Generated by Django 4.1.7 on 2023-05-08 09:42

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("the_archive", "0003_bookmark_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
