# Generated by Django 4.1.7 on 2023-05-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0004_alter_tag_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
