# Generated by Django 4.1.7 on 2023-05-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0005_alter_tag_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
