# Generated by Django 4.1.7 on 2023-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0007_delete_tags_alter_upload_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
