# Generated by Django 4.1.7 on 2023-05-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
