# Generated by Django 4.1.7 on 2023-05-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geolocation", "0001_initial"),
        ("the_archive", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AlterField(
            model_name="upload",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geolocation.location",
            ),
        ),
    ]
