# Generated by Django 4.1.7 on 2023-05-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0002_alter_upload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(max_length=255, null=True, upload_to=""),
        ),
    ]
