# Generated by Django 4.1.7 on 2023-05-08 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0002_alter_bookmark_tags_alter_upload_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="tags",
        ),
    ]
