# Generated by Django 4.1.7 on 2023-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0002_upload_user_alter_upload_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="upload",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="MediaType",
        ),
    ]
