# Generated by Django 4.1.7 on 2023-05-10 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0003_rename_name_tag_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
