# Generated by Django 4.1.7 on 2023-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0003_alter_upload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
