# Generated by Django 4.1.7 on 2023-05-07 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0008_alter_upload_upload_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upload",
            old_name="upload_file",
            new_name="file",
        ),
    ]
