# Generated by Django 4.1.7 on 2023-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0009_rename_upload_file_upload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="media_type",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
