# Generated by Django 4.1.7 on 2023-05-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0010_alter_upload_media_type"),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name="Tag",
        # ),
    ]
