# Generated by Django 4.1.7 on 2023-05-09 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0002_delete_location_alter_upload_location"),
        ("the_archive", "0011_alter_tag_name"),
    ]

    operations = []
