# Generated by Django 4.1.7 on 2023-05-10 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0003_alter_link_url_alter_upload_file"),
        ("the_archive", "0004_delete_tag"),
        ("the_archive", "0012_merge_20230509_1107"),
    ]

    operations = []
