# Generated by Django 4.1.7 on 2023-05-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0013_merge_20230510_1609"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.CharField(default="summer", max_length=255),
            preserve_default=False,
        ),
    ]
