# Generated by Django 4.1.7 on 2023-05-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0014_alter_upload_file_filebookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.CharField(max_length=255),
        ),
    ]
