# Generated by Django 4.1.7 on 2023-05-12 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0013_merge_20230512_0914"),
        ("the_archive", "0015_alter_upload_file"),
    ]

    operations = []
