# Generated by Django 4.1.7 on 2023-05-22 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0013_merge_20230510_1609"),
        ("the_archive", "0016_merge_0013_merge_20230512_0914_0015_alter_upload_file"),
    ]

    operations = []
