# Generated by Django 4.1.7 on 2023-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_archive", "0016_merge_20230516_1428"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
